# Generated by Django 6.0 on 2026-02-12 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('qualy_cargada', 'Qualy cargada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.carrera')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.piloto')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoQualy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.carrera')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.piloto')),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.carrera')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.piloto')),
            ],
            options={
                'unique_together': {('usuario', 'carrera')},
            },
        ),
    ]
