# Generated by Django 6.0 on 2026-02-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='puntos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('qualy_cargada', 'Qualy cargada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
    ]
