# Generated by Django 6.0 on 2026-02-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
